name: 'Upstream Sync'

on:
  schedule:
    - cron: '5 * * * *'
    # runs every 5th minute.

  workflow_dispatch:  # click the button on Github repo!

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        # optional: set the branch to checkout,
        # sync action checks out your 'target_sync_branch' anyway
        ref: master
        # REQUIRED if your upstream repo is private (see wiki)
        persist-credentials: false

    # Step 2: run the sync action
    - name: Sync upstream changes
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: master
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: master
        upstream_sync_repo: MUnique/OpenMU
        upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}

        # Set test_mode true to run tests instead of the true action!!
        test_mode: false
